### PR TITLE
REVERTME: Add camera read and write as supported combinations

### PR DESCRIPTION
**Pull request by JeevakaPrabu**
Signed-off-by: Saranya Gopal <saranya.gopal@intel.com>

### CODE REVIEW

**Comment by JeevakaPrabu** [comment]
@kalyankondapally @saranyagopal1

**Comment by kalyankondapally** [comment]
Can you check if this is still needed as NV12 should be in the supported list and also converted correctly to drm counterpart.

**Comment by JeevakaPrabu** [comment]
It is needed as the supported combination checks for format and the usage
flags. Currently, added usage flag is not enough for camera. Since the
usage flag various from clients(producer and consumer, camera intermediate
buffers etc), plan is to merge the REVERTME patch and add the right
combinations later

**Comment by JeevakaPrabu** [comment]
Proper fix will be delivered to address the issue

**Pull request closed without merging**
